apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mdm324fyg-python 
  janus-idp.io/tekton: mdm324fyg-python
  backstage.io/kubernetes-id: mdm324fyg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mdm324fyg-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  