apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mdm324fyg-python
  janus-idp.io/tekton: mdm324fyg-python
  backstage.io/kubernetes-id: mdm324fyg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mdm324fyg-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
